### ISSUE TITLE
"melatonin_vector/melatonin_vector.h" and other included files missing?

### ISSUE THREAD

**Issue by sharpobject** [sudara/melatonin_blur#15]
Hello,

I'd like to try doing this with a SIMD kernel or see what the existing implementations are doing, but it seems like the implementations are not checked in, because of the many missing header files! So I cannot see what they are doing and I cannot compare any new implementation to them.

**Comment by sudara** [comment]
Hi there,

Thanks for writing! Fantastic that you'd be interested in contributing.

Yes, a SIMD implementation would be great. There was some mention of interest here too: https://forum.juce.com/t/faster-blur-glassmorphism-ui/43086/93?u=sudara

Here are a few pieces of information:

* The current vector implementations are essentially all identical. So you can look at the FloatVectorOperations implementation or the IPP implementation if you are curious about the functions used
* They are all really basic things, add, subtract, divide. There's one "add with multiply" (accumulate) operation.
* If you have any questions, I can paste you bits of my melatonin_vector.h library — it's not published, but only because it would be hard to package up. It just uses vdsp and IPP under the hood, not SIMD

**Comment by sudara** [comment]
Ah, if the main interest is in benchmark comparison, I would recommend comparing against the vanilla stack blur implementation. Theres a copy in this repo called Gin. It integrates with JUCE and essentially is a modified copy of other C/C++ implementations. 

I use that as the baseline. My best single channel implementations so far is 4-5x on Windows and 10x on the latest macOS with vImage. The only vector implementations I’ve tried though are doing whole rows/cols at once. 

ARGB is the holy grail. Haven’t run into anything that outperforms Stack Blur except for the latest vImage on macOS.

**Comment by sharpobject** [comment]
Great! For ARGB, do I need to un-premultiply, then blur, then re-premultiply?

**Comment by sudara** [comment]
I’ve been operating under the assumption that the source RGB data is already pre-multiplied and it’s “good” to operate on that. The reference implementations seem to treat all 4 channels the same. 

But to be honest, I’m unclear about the specifications or implications of blurring a semi-transparent image!

For the common ARGB case (big ole nice image blur) the alpha will just be the same for every pixel, and in most cases that will just be 255.

**Comment by sudara** [comment]
I got the tests running in CI, which also means that locally, they should run without complaining about missing headers!

Some of the implementations do still require melatonin_vector, but I'll close this for now since it should be resolved for the binaries. Feel free to ask me other stuff tho!
